### ISSUE TITLE
error 커밋에서

### ISSUE THREAD

**Issue by Woongstar** [Yummy-sk/inflearn-chat-app#3]
localhost~~/register 주소로 들어갔는데도 hi 만뜨고 내가 넣은 회원가입 UI는 나오지가 않음

**Comment by Yummy-sk** [comment]
Switch는 가장 맨앞에 있는 매칭되는 컴포넌트를 반환합니다. 그러기에 앞에 <div>~~</div>를 넣으면, 이게 /로 판단하는것 같은데 자세한거는 Switch 공부해보세요!!
